In [17]:
import numpy as np
import matplotlib.pyplot as plt
import time
import tensorflow as tf
from scipy.special import erfc

In [22]:
# Now we will try to implement a Fourier Transform and Analysis of Nick's Formula
# First define the function one needs to transform
def L(sigma, mu, Y):
    return (sigma/np.sqrt(2*mu) + sigma**2 * Y**2)

def g(x, y, x1, y1, sigma, mu, rho, B, Y):
    fac1 = np.exp(1j * (y - y1)*Y) 
    fac2 =8 * np.pi * sigma * rho * np.sqrt(2 * mu + sigma**2 * Y **2)
    fac3 = 2 * L(sigma, mu, Y) / (2 * L(sigma, mu, Y) + B)
    return fac1 * fac3 / fac2

# This finishes the Implementation of Nick's function for
# different sides of the Barrier.

In [23]:
g(-1,0,1,0,1,1,1,1,1)

(0.017767930850719312+0j)

In [24]:
np.pi

3.141592653589793

In [25]:
def a(x):
    y = x
        /2
    return y
a(2)

IndentationError: unexpected indent (<ipython-input-25-9eb6b0fb4748>, line 3)

In [53]:
print("Lololol")

Lololol


In [54]:
print("uuuhyeah")

uuuhyeah


In [71]:
n=10
a=np.ones((n,n))*0.5

In [76]:
mean = [np.random.multivariate_normal(n*[0],a)[0] for _ in range(1000)]
np.var(mean)

0.52700853649603485

In [2]:
time.time()

1487604277.51406

In [5]:
x = np.array([1.2, -3.4, -3.4])

In [6]:
np.abs(x)

array([ 1.2,  3.4,  3.4])

In [3]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [4]:
import multiprocessing as mp
import numpy as np

In [2]:
mp.cpu_count()

4

In [42]:
a = np.reshape(np.arange(16),(4,4))
np.transpose(inds), inds

(array([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 2],
        [2, 3],
        [3, 3]]),
 (array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3]),
  array([0, 1, 2, 3, 1, 2, 3, 2, 3, 3])))

In [53]:
inds=np.triu_indices(4)
inds1=np.tril_indices(4)

b=np.zeros((4,4))
b[inds]=a[inds]/2.0
c=np.triu(b)+np.triu(b,-1).T - np.diag(np.diag(b))

print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0. ,  0.5,  1. ,  1.5],
       [ 0.5,  2.5,  3. ,  3.5],
       [ 1. ,  3. ,  5. ,  5.5],
       [ 1.5,  3.5,  5.5,  7.5]])

In [15]:
a=str(1).zfill(2)
a

'01'

In [20]:
a= np.array([1,2,3])
np.savetxt("./test/delete_this.csv", a, delimiter ="$")

IOError: [Errno 2] No such file or directory: './test/delete_this.csv'

In [21]:
import os

In [23]:
os.listdir("./")

['results',
 'Data',
 'analysis.pyc',
 'Area51.ipynb',
 '.ipynb_checkpoints',
 '.git',
 'kernels.pyc',
 'Laplace_all_loci.ipynb',
 'multi_run.py',
 'grid.pyc',
 'forward_sim.py',
 'forward_sim.pyc',
 'temp_save.p',
 'README.md',
 '.project',
 'kernels.ipynb',
 'fourier_kernel.ipynb',
 'tf_analysis.py',
 'grid.py',
 'GPR_kernelfit.py',
 'Laplace.ipynb',
 'kernels.py',
 'main.py',
 'Laplace-Copy2.ipynb',
 'GPR_kernelfit.pyc',
 'tf_analysis.pyc',
 '.pydevproject',
 'Laplace-Copy1.ipynb',
 'area53.py',
 '.gitignore',
 'mle_class.py',
 '.settings',
 'script_mr.py',
 'data_lists.p',
 'analysis.py',
 'diff_test_barrier.py']